demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ezdemo/', include('ezlearn.urls'))
]+ static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ezlearn/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('hello/', views.say_hello, name='say_hello'),
    #main
    # using pyotp functioning
    path('otp_validate/', views.otp_validating, name ='otp_validate'),
    path('learner_register/', views.learner_registration, name='learner_registration'),

    #end of pyotp
    path('l_login/', views.learner_login, name='learner_login'),
    path('l_register/', views.register_learner, name='register_learner'),
    path('otp/', views.otp_view, name='otp'),
    path('validate_lregistration/', views.valdate_lregistration, name='validate_lregistration'),
    path('complete_profile/<int:id>',views.complete_profile ,name='complete_profile'),
    path('learner_profile/<int:id>', views.learner_profile, name='learner_profile'),
    path('logout/', views.leaner_logout, name='logout'),

    #developer
    path('d_login/', views.developer_login, name='developer_login'),
    path('d_register/', views.register_developer, name='register_developer'),
    path('dotp/', views.developer_otp_view, name='dotp'),
    path('validate_dregistration/', views.valdate_dregistration, name='validate_dregistration'),
    path('d_home/<int:id>', views.developer_home, name='developer_home'),
    path('learner_list/<int:id>', views.learners_list, name='learners_list'),
    path('courses_list/<int:id>', views.courses_list, name='courses_list'),
    path('quiz_list/<int:id>', views.quiz_list, name='quiz_list'),
    path('add_course/<int:id>', views.add_course, name='add_course' ),
    path('delete_course/<int:id>/<int:did>', views.delete_course, name='delete_course'),
    path('create_quiz/<int:id>', views.quiz_creation_view, name='create_quiz'),
    path('delete_quiz/<int:id>/<int:did>', views.delete_quiz, name='delete_quiz'),
    path('developer_logout', views.developer_logout, name='d_logout'),

    #course

    path('home/<int:id>', views.home, name='home'),
    path('inside_course/<int:id>/<int:cid>', views.learning_course, name='learn_course'),

    #quiz

    path('get_quiz/<str:title>/<int:id>/', views.get_into_quiz, name='get_quiz' ),
    path('quiz/<str:title>/<int:id>/', views.take_quiz_view, name='take_quiz'),
   

    #payments
    path('check_payment/<int:id>/<str:name>', views.check_payment, name='check_payment'),
    path('making_payment/<int:id>', views.making_payment, name='making_payment'),
    path('confirm_payment/<int:id>/<int:lid>', views.confirm_payment, name='confirm_payment'),
    path('verify', views.verify, name='verify'),
    
    #compiler
    path('run/<int:id>', views.runcode, name='runcode'),
    path('index/<int:id>', views.index, name='index'),
    #course
    path('frame',views.frame,name='frame'),

    #certification
    path('get_certificate/<int:id>/<int:cid>', views.get_certificate, name='get_certificate'),
    
    #other
    path('profile/', views.show_profile, name='profile'),
    path('quiz_submissions/<int:id>', views.quiz_submissions_view, name='quiz_submissions'),

]

ezlearn/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class learners(models.Model):
        username = models.CharField(max_length=50)
        first_name = models.CharField(max_length=50, default='')
        last_name = models.CharField(max_length=50, default='')
        profile_picture = models.ImageField(null=True, upload_to='images/')
        email = models.EmailField()
        ph_number = models.CharField(max_length=15, blank=True, null=True)
        DOB = models.DateField( null = True, default='2001-01-01')
        user = models.OneToOneField(User, on_delete=models.CASCADE, default=None)
        dno = models.CharField(max_length=100, null=True, blank=True, default='')
        street = models.CharField(max_length=100, null=True, blank=True, default='')
        city = models.CharField(max_length=100, null=True, blank=True, default='')
        state = models.CharField(max_length=100, null=True, blank=True, default='')
        country = models.CharField(max_length=100, null=True, blank=True, default='')
        pincode = models.CharField(max_length=100, null=True, blank=True, default='')

        def __str__(self):
                return f'{self.username}'


class developer(models.Model):
        developer_name = models.CharField(max_length=50)
        email = models.EmailField()
        user = models.OneToOneField(User, on_delete=models.CASCADE , default=None)

        def __str__(self):
                return f'{self.developer_name}'
        

class Course(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    price = models.IntegerField()
    discount = models.IntegerField( null=True, blank=True)
    def __str__(self):
         return f'{self.name}'
    
class learnings(models.Model):
    learner = models.ForeignKey(learners, on_delete=models.CASCADE, default=None)
    course_learning = models.OneToOneField(Course, on_delete=models.CASCADE, default=None)
    activation = models.BooleanField(default=False)

    def __str__(self):
          return f'{self.learner}'
    

class Payment(models.Model):
    order_id = models.CharField(max_length=300, null=True, blank= True)
    payment_id = models.CharField(max_length=300, null=True, blank=True)
    status = models.BooleanField(default=False)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    learner = models.ForeignKey(learners, on_delete=models.CASCADE , default=0)


    def __str__(self):
         return self.order_id

class Quiz(models.Model):
    title = models.CharField(max_length=255)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.title

class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question_number = models.IntegerField()
    question = models.CharField(max_length=255)

    def __str__(self):
        return self.question

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.choice
    

class Submission_quiz(models.Model):
    Learner = models.ForeignKey(learners, on_delete=models.CASCADE)
    Quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE )
    score = models.IntegerField(blank=True, null=True, default = 0)
    questions = models.JSONField(default=list)
    selected_choices = models.JSONField(default=dict)

    def __str__(self):
        return self.Learner.username




# class quiz_result(models.Model):
#     attempt_no = models.IntegerField()
#     total = models.IntegerField(null=True, blank=True)
#     learner = models.ForeignKey(learners, on_delete=models.CASCADE)

#     def __str__(self):
#          return self.attempt_no
    
# class questions_review(models.Model):
#     question_name = models.CharField(max_length=500)
#     option1 = models.CharField(max_length=300 ,null=True, blank=True)
#     option2 = models.CharField(max_length=300 ,null=True, blank=True )
#     option3 = models.CharField(max_length=300 ,null=True, blank=True)
#     option4 = models.CharField(max_length=300 ,null=True, blank=True )
#     correct = models.CharField(max_length=300 ,null=True, blank=True)

ezlearn/forms.py
from django import forms
from .models import learners

class imageForm(forms.Form):
    profile_picture = forms.ImageField()

ezlearn/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required, permission_required
from .utils import send_otp
from django.core.mail import send_mail
from datetime import datetime
import pyotp
from django.contrib.auth.models import User, Group
from .models import learners
from .models import developer as D
from .models import Course, learnings, Quiz, Question, Choice, Payment
from .models import Submission_quiz
import math
import random
import sys
import razorpay
from demo.settings import KEY_ID,KEY_SECRET
from django.views.decorators.csrf import csrf_exempt
from .forms import imageForm
from django.template.loader import get_template
from xhtml2pdf import pisa





def say_hello(request):
    return HttpResponse(f'hello')

# Create your views here.

#sending main while logged in
def sending_mail(message, otp, email):
    if otp != '':
        send_mail("hello somu", f'{message} {otp}', "somasekhar_devisetty3@gmail.com",[email])
    else:
        send_mail("hello somu", f'{message}', "somasekhar_devisetty3@gmail.com",[email])


def generateOTP():
    digits = "0123456789"
    OTP = ""
    for i in range(6) :
        OTP += digits[math.floor(random.random() * 10)]
    return OTP


#compiler
def index(request, id):
    learner = learners.objects.get(id=id)
    return render(request, 'compiler/pycompiler.html', {'learner':learner})


def runcode(request, id):
    learner = learners.objects.get(id=id)
    if request.method == "POST":
        codeareadata = request.POST['codearea']
        try:
            orig_stdout = sys.stdout
            sys.stdout = open('file.txt', 'w')
            exec(codeareadata)
            sys.stdout.close()
            sys.stdout=orig_stdout
            output = open('file.txt', 'r').read()
        except Exception as e:
            sys.stdout=orig_stdout
            output = e
    return render(request , 'compiler/pycompiler.html', {"code":codeareadata , "output":output, 'learner':learner})


def main(request):
    return render(request, 'main_template.html')

# final funtion for registering a learner (from here)
def register_learner(request):
    if request.method == 'POST':
        request.session['username'] = request.POST['username']
        request.session['firstname'] = request.POST['firstname']
        request.session['lastname'] = request.POST['lastname']
        request.session['email'] = request.POST['email']
        request.session['password'] = request.POST['password']
        request.session['otp'] = generateOTP()
        print(request.session['otp'])
        message = 'your otp to complete the registration of ez_learn is '
        print(message)
        sending_mail(message, request.session['otp'], request.session['email'])
        return redirect('otp')
    return render(request, 'learner_register.html')

def otp_view(request):
    return render(request, 'otp.html')

def valdate_lregistration(request):
    context = {}
    if request.method == 'POST':
        entered_otp = request.POST['otp']
        try:
            if entered_otp == request.session['otp']:
                username= request.session['username']
                firstname = request.session['firstname']
                lastname = request.session['lastname']
                email = request.session['email']
                password = request.session['password']
                user = User.objects.create_user(username = username , password = password)
                learner = learners.objects.create(username = username, first_name= firstname, last_name = lastname, email = email, user = user)
                courses = Course.objects.all()
                for course in courses:
                    learnings_ = learnings.objects.create(learner=learner, course_learning=course)
                return render(request, 'learner/successful.html' ,{'learner' : learner})
            else:
                context['error_message'] = 'enter valid otp'
        except:
            error = 'Username already exist'
            return render(request, 'learner_register.html', {'error': error})
    return render(request, 'otp.html', context)

#complete profile
def complete_profile(request, id):
    learner = learners.objects.get(id=id)
    if request.method == 'GET':
        print(learner)
        form = imageForm()
        print(form)
        return render(request, 'personal.html', {'learner':learner, 'form': form})
    if request.method == 'POST':
        form = imageForm(request.POST, request.FILES)
        if form.is_valid():
            img = form.cleaned_data.get('profile_picture')
            print(img)
            learner.dno = request.POST.get('house_no')
            learner.street = request.POST.get('street')
            learner.city = request.POST.get('city')
            learner.state = request.POST.get('state')
            learner.country = request.POST.get('country')
            learner.pincode = request.POST.get('pincode')
            learner.ph_number= request.POST.get('phone_no')
            learner.DOB = request.POST.get('dob')
            learner.profile_picture = img
            learner.save()
            return redirect('learner_login')
        


#learner login function
def learner_login(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        u = authenticate(username= username , password = password)
        if u is not None:
            learner = learners.objects.get(user = u)
            email = learner.email
            #message = 'you just logged into you ezlearn account'
            #sending_mail(message,'',email)
            login(request, u)
            courses = Course.objects.all()
            return redirect('home' , learner.id)
        else:
            context['error'] = 'wrong username or password'
    return render(request, 'learner_login.html', context)

# home page of learner
@login_required
def home(request, id):
    learner = learners.objects.get(id=id)
    courses = Course.objects.all()
    return render(request, 'learner/home.html', {
                                                        'learner': learner,
                                                        'courses' : courses 
                                                        })




#getting learner's personal details
def learner_profile(request, id):
    learner = learners.objects.get(id =id)
    return render(request, 'learner/profile.html', {'learner' : learner})


#getting into a particular course

def learning_course(request, id, cid):
    learner = learners.objects.get(id = id)
    course = Course.objects.get(id = cid)
    if course.name == 'PYTHON':
        return render(request, 'python.html', {'learner': learner, 'course': course})
    elif course.name == 'HTML':
        return render(request, 'html.html', {'learner': learner, 'course': course})
    elif course.name == 'CSS':
        return render(request, 'css.html', {'learner': learner, 'course': course})






#playing quiz
#quiz/views.py

def get_into_quiz(request, title, id):
    learner = learners.objects.get(id=id)
    course = Course.objects.get(name=title)
    quiz = Quiz.objects.get(course=course)
    try:
        submissions = Submission_quiz.objects.filter(Learner= learner,  Quiz  = quiz)
        return render(request, 'quiz/quizs_played.html', {'learner':learner, 'course' : course, 'submissions': submissions})
    except:
        return render(request, 'quiz/quizs_played.html', {'learner':learner, 'course' : course})

def take_quiz_view(request, title, id):
    learner = learners.objects.get(id=id)
    course = Course.objects.get(name=title)
    print(learner.username)
    quiz = Quiz.objects.get(course=course)
    questions = Question.objects.filter(quiz=quiz)

    if request.method == 'POST':
        submitted_answers = [request.POST.get(str(question.id)) for question in questions]
        score = 0
        results = []
        selected_choices = {}
        for i in range(len(questions)):
            question = questions[i]
            correct_choice = Choice.objects.get(question=question, is_correct=True)
            submitted_answer = submitted_answers[i]

            if submitted_answer == str(correct_choice.id):
                score += 1

            choices = question.choice_set.all()
            options = [choice.choice for choice in choices]

            result = {
                'question_number':question.question_number,
                'options' : options,
                'question_text': question.question,
                'submitted_answer': Choice.objects.get(id=submitted_answer).choice if submitted_answer else 'Not answered',
                'correct_answer': correct_choice.choice,
            }
            results.append(result)
            selected_choices[str(question.id)] = submitted_answer

        submissions = Submission_quiz.objects.create(Learner=learner, Quiz= quiz, score = score, questions = list(questions.values_list('id', flat=True)), selected_choices = selected_choices)
        context = {'quiz': quiz, 'questions': questions, 'results': results, 'score': score, 'learner':learner}
        return render(request, 'quiz/result.html', context)

    return render(request, 'quiz/take_quiz.html', {'quiz': quiz, 'questions': questions, 'course':course, 'learner':learner})



#generating certificate
def get_certificate(request, id , cid):
    learner = learners.objects.get(id = id)
    course = Course.objects.get(id = cid)
    quiz_ = Quiz.objects.filter(course = course)
    quiz = quiz_[0]
    try:
        submissions = Submission_quiz.objects.filter(Learner = learner, Quiz = quiz)
        maximum_score = max([submission.score for submission in submissions])
        if maximum_score >= 3 :

ezlearn/templates/developer/add_course.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <title>Add Course Form</title>
    <link rel="stylesheet" href="{% static 'home.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <style>
        h2 {
            color: #336699;
        }

        form {
            background-color: #ffffff;
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5);
        }

        label {
            display: block;
            color: #336699;
            margin-bottom: 5px;
        }

        input[type="text"],
        input[type="number"],
        textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 4px;
            outline: none;
        }

        textarea {
            resize: vertical;
            min-height: 100px;
        }

        .button {
            padding: 10px 20px;
            background-color: #336699;
            color: #ffffff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        .button:hover {
            background-color: #004466;
        }
    </style>
</head>
<body>
    <header>
        <div class="nav">
          
          <div class="logo">
            <img src="{% static 'ezlogo.jpeg' %}" alt="Logo">
          </div>
          <div class="profile">
            <h6 class="name" ><a style="color: aliceblue;" href="{% url 'd_logout'%}">logout</a></h6>
            <h3 class="name">{{developer.developer_name}}</h3>
          </div>
        </div>
      </header>
    <div style="padding-top: 120px;width: 90vw;margin-left: 20px;margin-bottom: 100px;">

    <h2>Add Course</h2>
    <form action="{% url 'add_course' developer.id %}" method="post">
        {% csrf_token %}
        <label for="course_name">Course Name:</label>
        <input type="text" id="course_name" name="course_name" required>

        <label for="course_description">Course Description:</label>
        <textarea id="course_description" name="course_description" rows="4" required></textarea>

        <label for="course_price">Course Price:</label>
        <input type="number" id="course_price" name="course_price" min="0" step="0.01" required>

        <label for="course_discount">Course Discount (%):</label>
        <input type="number" id="course_discount" name="course_discount" min="0" max="100" step="1" required>

        <input type="submit" value="Add Course" class="button">
    </form>
    <a href="{% url 'courses_list' developer.id %}"></a>
</div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

</body>
</html>

ezlearn/templates/developer/quiz_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>learners list</title>
    <link rel="stylesheet" href="{% static 'home.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <style>
        h1 {
            color: #3498db;
        }

        table {
            counter-reset: row-counter;
            border-collapse: collapse;
            width: 100%;
            margin-top: 20px;
            background-color: #3498db;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            border-radius: 10px;
            color:black;
        }

        th, td {
            border: 1px solid #dddddd;
            padding: 12px;
            text-align: left;
        }

        th {
            background-color: #2980b9;
        }

        tr:nth-child(even) {
            background-color: #85c1e9;
        }

        tr:hover {
            background-color: #aed6f1;
        }

        td:first-child:before {
            counter-increment: row-counter;
            content: counter(row-counter);
        }
    </style>
</head>
<body>
    <header>
        <div class="nav">
          
          <div class="logo">
            <img src="{% static 'ezlogo.jpeg' %}" alt="Logo">
          </div>
          <div class="profile">
            <h6 class="name" ><a style="color: aliceblue;" href="{% url 'd_logout'%}">logout</a></h6>
            <h3 class="name">{{developer.developer_name}}</h3>
          </div>
        </div>
      </header>
    <div style="padding-top: 100px;width: 100vw;display: flex;flex-direction: column;align-items: center;">
        <h1>Quizzes List</h1>
        <div style="width: 80vw;">
        <table>
            <tr>
                <th>#</th>
                <th>Quiz Title</th>
                <th>course</th>
                <th>max_score</th>
            </tr>
            {% for course in courses %}
                {% for quiz in course.quiz_set.all %}
                <tr>
                    <td></td>
                    <td>{{quiz.title}} Quiz</td>
                    <td>{{quiz.course.name}}</td>
                    <td>20</td>
                    <td><a style="color: white;" href="{% url 'delete_quiz' quiz.id developer.id %}">delete</a></td>
                </tr>
                {% endfor %}
            {% endfor %}
        </table>
    </div>
    </div>
    <a href="{% url 'create_quiz' developer.id %}"><h4 style="color:whitesmoke;margin-left: 100px;margin-top:20px;background-color:blue;width: fit-content;padding: 10px;border-radius: 20px;">Add Quiz</h4></a>
    <a href="{% url 'developer_home' developer.id %}"><h4 style="color:whitesmoke;margin-left: 100px;margin-top:20px;background-color:blue;width: fit-content;padding: 10px;border-radius: 20px;">Back</h4></a>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

ezlearn/templates/developer/successful.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <title>Registration Successful Message Example</title>

    <meta name="author" content="Codeconvey" />
    <!-- Message Box CSS -->
    <link rel="stylesheet" href="{% static 'successful.css' %}">
    <!--Only for demo purpose - no need to add.-->
  
	
</head>
<body>
<section>
    <div class="rt-container">
          <div class="col-rt-12">
              <div class="Scriptcontent">
              
<!-- partial:index.partial.html -->
<div id='card' class="animated fadeIn">
  <div id='upper-side'>
    <?xml version="1.0" encoding="utf-8"?>
      <!-- Generator: Adobe Illustrator 17.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
      <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
      <svg version="1.1" id="checkmark" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" xml:space="preserve">
        <path d="M131.583,92.152l-0.026-0.041c-0.713-1.118-2.197-1.447-3.316-0.734l-31.782,20.257l-4.74-12.65
	c-0.483-1.29-1.882-1.958-3.124-1.493l-0.045,0.017c-1.242,0.465-1.857,1.888-1.374,3.178l5.763,15.382
	c0.131,0.351,0.334,0.65,0.579,0.898c0.028,0.029,0.06,0.052,0.089,0.08c0.08,0.073,0.159,0.147,0.246,0.209
	c0.071,0.051,0.147,0.091,0.222,0.133c0.058,0.033,0.115,0.069,0.175,0.097c0.081,0.037,0.165,0.063,0.249,0.091
	c0.065,0.022,0.128,0.047,0.195,0.063c0.079,0.019,0.159,0.026,0.239,0.037c0.074,0.01,0.147,0.024,0.221,0.027
	c0.097,0.004,0.194-0.006,0.292-0.014c0.055-0.005,0.109-0.003,0.163-0.012c0.323-0.048,0.641-0.16,0.933-0.346l34.305-21.865
	C131.967,94.755,132.296,93.271,131.583,92.152z" />
        <circle fill="none" stroke="#ffffff" stroke-width="5" stroke-miterlimit="10" cx="109.486" cy="104.353" r="32.53" />
      </svg>
      <h3 id='status'>
      Success
    </h3>
  </div>
  <div id='lower-side'>
    <p id='message'>
      Congratulations, your account has been successfully created.
    </p>
    <a href="{% url 'developer_login' %}" id="contBtn">Login to Continue</a>
  </div>
</div>
<!-- partial -->
    		
           
    		</div>
		</div>
    </div>
</section>
     


    <!-- Analytics -->

	</body>
</html>